spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_product
    username: root
    password: 14640548root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    security:
      enabled: false

  application:
    name: product-service

server:
  port: 9093
  servlet:
    context-path: /product-service

application:
  config:
    trace: true

validate:
  token:
    url: http://localhost:8080/validateToken?token=