spring:
  datasource:
    url: jdbc:mysql://api.prism-sfa-dev.net:3306/sfa_db
    username: PrismSfa
    password: TestUser123!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    security:
      enabled: false

  application:
    name: product-service

server:
  port: 9093
  servlet:
    context-path: /product-service

application:
  config:
    trace: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

validate:
  token:
    url: http://localhost:9094/auth-service/auth/validateToken?token=