package sfa.product_service.constant;

public enum UserRole {
    Create_Manager,
    Edit_Manager,
    Delete_Manager,
    Manager,
    View_Manager,
    ClientFMCG,
    Reporting_Manager,
    Super_Admin,
    Create_Inventory,
    Edit_Inventory,
    Delete_Inventory,
    View_Inventory,
    Create_product,
    Delete_product,
    View_product,
    Edit_product,
    Create_Order, Edit_Order, Delete_Order, View_Order,
    Create_Item, Edit_Item, Delete_Item, View_Item,
    Create_Report, Edit_Report, Delete_Report, View_Report,
    Create_Salesreturn, Edit_Salesreturn, Delete_Salesreturn, View_Salesreturn,
    Create_Transaction, Edit_Transaction, Delete_Transaction, View_Transaction,
    Create_Attendance,Edit_Attendance,Delete_Attendance,View_Attendance,
    Create_Beet,Edit_Beet,Delete_Beet,View_Beet,
    Create_BeatJourneyPlan,Edit_BeatJourneyPlan,Delete_BeatJourneyPlan,View_BeatJourneyPlan,
    Create_BeatJourneyPlanLog,Edit_BeatJourneyPlanLog,Delete_BeatJourneyPlanLog,View_BeatJourneyPlanLog,
    Create_Candidate,Edit_Candidate,Delete_Candidate,View_Candidate,
    Create_Category,Edit_Category,Delete_Category,View_Category,
    Create_City,Edit_City,Delete_City,View_City,
    Create_Csv,Edit_Csv,Delete_Csv,View_Csv,
    Create_DailyStatus,Edit_DailyStatus,Delete_DailyStatus,View_DailyStatus,
    Create_Dcr,Edit_Dcr,Delete_Dcr,View_Dcr,
    Create_Department,Edit_Department,Delete_Department,View_Department,
    Create_Designation,Edit_Designation,Delete_Designation,View_Designation,
    Create_Distance,Edit_Distance,Delete_Distance,View_Distance,
    Create_Division,Edit_Division,Delete_Division,View_Division,
    Create_Expense,Edit_Expense,Delete_Expense,View_Expense,
    Create_FileUpload,Edit_FileUpload,Delete_FileUpload,View_FileUpload,
    Create_Holidays,Edit_Holidays,Delete_Holidays,View_Holidays,
    Create_Leave,Edit_Leave,Delete_Leave,View_Leave,
    Create_Member,Edit_Member,Delete_Member,View_Member,
    Create_MemberPermission,Edit_MemberPermission,Delete_MemberPermission,View_MemberPermission,
    Create_MemberSalary,Edit_MemberSalary,Delete_MemberSalary,View_MemberSalary,
    Create_Outlet,Edit_Outlet,Delete_Outlet,View_Outlet,
    Create_PrimarySales,Edit_PrimarySales,Delete_PrimarySales,View_PrimarySales,
    Create_ProductDetails,Edit_ProductDetails,Delete_ProductDetails,View_ProductDetails,
    Create_Product,Edit_Product,Delete_Product,View_Product,
    Create_PurchaseOrder,Edit_PurchaseOrder,Delete_PurchaseOrder,View_PurchaseOrder,
    Create_Region,Edit_Region,Delete_Region,View_Region,
    Create_SecondarySale,Edit_SecondarySale,Delete_SecondarySale,View_SecondarySale,
    Create_State,Edit_State,Delete_State,View_State,
    Create_Client,Edit_Client,Delete_Client,View_Client,
    Create_Client_FMCG,Edit_Client_FMCG,Delete_Client_FMCG,View_Client_FMCG
}